FROM php:8.1-apache-buster

LABEL maintainer="Rye Miller" \
      vendor="The Dark Society <containers@darksociety.io>" \
      version="0.1" \
      org.label-schema.name="thedarksociety/php" \
      org.label-schema.description="PHP-Apache v8.2 Apache Buster" \
      org.label-schema.build-date="2024-11-18" \
      org.label-schema.schema-version="0.1" \
      org.label-schema.vcs-url="https://github.com/thedarksociety/docker-php"
      org.opencontainers.image.title="PHP-Apache v8.0 Apache Buster"
      org.opencontainers.image.url="https://github.com/thedarksociety/docker-php/apache/8.1" \
      org.opencontainers.image.source=""
      org.opencontainers.image.documentation="https://github.com/thedarksociety/docker-php/README.md"

ARG DEBIAN_FRONTEND=noninteractive
ARG TIMEZONE="America/Denver"

ENV TZ $TIMEZONE
