FROM php:8.4-fpm

LABEL \
  maintainer="The Dark Society <containers@darksociety.cloud" \
  vendor="The Dark Society" \
  version="0.1.0" \
  org.label-schema.name="thedarksociety/php" \
  org.label-schema.build-date="2024-12-09" \
  org.label-schema.schema-version="0.1.0" \
  org.label-schema.vcs-url="https://github.com/thedarksociety/docker-php"
  org.opencontainers.image.title="PHP-FPM v8.4"
  org.opencontainers.image.url="https://github.com/thedarksociety/docker-php/8.4/fpm" \
  org.opencontainers.image.documentation="https://github.com/thedarksociety/docker-php/README.md"
